version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.15.0
    container_name: config-consul
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    ports:
      - "8500:8500"
      - "8300:8300"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - consul-data:/consul/data
    healthcheck:
      test: ["CMD", "consul", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: always

  alatiprojekat2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alatiprojekat2
    ports:
      - "8080:8080"
    environment:
      CONSUL_ADDRESS: "consul:8500"
    depends_on:
      consul:
        condition: service_healthy
    restart: always

volumes:
  consul-data: